"===========================================================================
"DESCRIPTION:自用vimrc文件，for Linux
"
"Last Change:2017年10月11日
"
"Version:1.2
"
"===========================================================================

    " Vim-Plugin Manager
    " Specify a directory for plugins
    " - Avoid using standard Vim directory names like 'plugin'
    if empty(glob('~/.vim/autoload/plug.vim'))
        silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
            \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    endif
    call plug#begin('~/.vim/vim_plugin')

    " Make sure using single quotes
    " Shorthand notation for full URL.
    Plug 'altercation/vim-colors-solarized'
    Plug 'iCyMind/NeoSolarized'
    " Plug 'flazz/vim-colorschemes'            "主题合集
    Plug 'vim-airline/vim-airline'                             " 状态栏
    Plug 'vim-airline/vim-airline-themes'                      " airline 主题
    " Plug 'edkolev/promptline.vim'                              " bash 提示符
    " Plug 'edkolev/tmuxline.vim'                                " tmux 提示栏
    Plug 'yianwillis/vimcdoc'                                  " 中文帮助文档
    Plug 'scrooloose/nerdtree',{'on':'NERDTreeToggle'}         " 文件树浏览
    Plug 'majutsushi/tagbar',{'on':['Tagbar', 'TagbarToggle', 'TagbarOpen']} " 文件结构
    Plug 'tpope/vim-fugitive'                                  " 管理 Git 仓库

    Plug 'SirVer/ultisnips'                                    " 代码块补全
    Plug 'honza/vim-snippets'                                  " 配合 ultisnips
    Plug 'w0rp/ale'                                            " 异步语法检查
    Plug 'chiel92/vim-autoformat'                              " 自动格式化代码
    Plug 'hotoo/pangu.vim'                                     " 自动格式化、标准化中文排版

    Plug 'scrooloose/nerdcommenter'                            " 批量、快速注释
    Plug 'easymotion/vim-easymotion'                           " 快速查找定位
    Plug 'haya14busa/incsearch.vim'                            " 增量搜索
    Plug 'haya14busa/incsearch-fuzzy.vim'                      " 模糊增量搜索
    Plug 'haya14busa/incsearch-easymotion.vim'                 " 增量搜索与 easymotion 结合
    Plug 'Yggdroot/indentLine'                                 " 自动显示缩进线

    Plug 'skywind3000/asyncrun.vim',{'on':'AsyncRun'}          " 异步后台编译运行

    " Plug 'lervag/vimtex',{'for': 'tex'}                        " Latex 插件
    Plug 'lervag/vimtex'                                       " Latex 插件
    Plug 'junegunn/vim-easy-align'                             " 对齐排版工具
    Plug 'Raimondi/delimitMate'                                " 括号配对
    Plug 'plasticboy/vim-markdown',{'for': 'markdown'}         " 高亮 Markdown, 依赖 tabular
    Plug 'iamcco/mathjax-support-for-mkdp',{'for': 'markdown'} " 预览数学公式
    Plug 'iamcco/markdown-preview.vim',{'for':'markdown'}      " 实时预览 Markdown
    Plug 'jszakmeister/markdown2ctags',{'for':'markdown'}

    Plug 'tomedunn/vim.modfortran'
    Plug 'kchmck/vim-coffee-script'
    Plug 'spiedeman/keylayout-vim-osx'

    " On-damand loading of plugins
    function! BuildYCM(info)
        " info is a dictionary with 3 fields
        " - name:	name of plugin
        " - status: 'installed', 'updated', or 'unchanged'
        " - force:  set on  PlugInstall! or PlugUpdate!
        if a:info.status ==? 'installed' || a:info.force
            !cd ~/.vim/vim_plugin/YouCompleteMe
            !./install.py --clang-completer --build-dir=$HOME/ycm_build
            !rm -rf ~/ycm_build
            "!bash ~/scripts/vim/youcompleteme.sh
            " !bash ~/config/youcom.sh "for ITP
        endif
    endfunction
    Plug 'Valloric/YouCompleteMe',	{'do': function('BuildYCM'), 'on': []} " 强大的自动补全
    " Plug 'tenfyzhong/CompleteParameter.vim'
    Plug 'junegunn/fzf', {'do': './install --all'}               " 强大的文件搜索

    " Initialize plugin system
    call plug#end()


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                              Vim Env                               "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
    " 设置中文帮助
    set helplang=cn
    " Multi-language 
    if has('multi_byte')
        " UTF-8 encoding 
        set encoding=utf-8
        set termencoding=utf-8
        set formatoptions+=nM
        set fileencodings=utf-8,gbk
        scriptencoding utf-8
        
        " if v:lang =~? '^\(zh\)\|\(ja\)\|\(ko\)'
        "     " set ambiwidth=double
        "     set ambiwidth=single
        " endif
    else 
        echoerr 'Sorry, this version of (g)vim was not compiled with +multi_byte'
    endif 
    " Doc directory 
    let helptags=$HOME.'/.vim/doc'
    if has('mouse_sgr')
        set ttymouse=sgr
    endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                              Vim GUI                               "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Basic Setting
    function! BasicSetting()
        set number             "显示行号
        " set nocompatible       "与vi不兼容
        set cursorline         "突出显示当前行
        set cursorcolumn       "突出显示当前列
        set ruler              "打开状态栏标尺
        set showcmd            "输入的命令显示出来
        set wildmenu
        set shiftwidth=4       "设定<<和>>命令移动时的宽度为4
        set softtabstop=4      "使得按退格键时可以一次删掉4个空格
        set tabstop=4          "设定tab长度为4
        set expandtab          "修改tab为4个空格
        " set autoindent
        set regexpengine=1
        " set relativenumber
        set lazyredraw
        set ttyfast
        set synmaxcol=200
        set nobackup           "覆盖文件时不备份
        set autochdir          "自动切换当前目录为当前文件所在的目录
        set backupcopy=yes     "设置备份时的行为为覆盖
        " set nowrapscan         "禁止在搜索到文件两端时重新搜索
        set incsearch          "增量搜索
        set hlsearch           "高亮显示搜索结果
        set ignorecase         "搜索时忽略大小写
        set smartcase          "但有一个及以上大小写时仍对其敏感

        set noerrorbells       "关闭错误信息响铃
        set novisualbell       "关闭使用可视响铃代替呼叫
        set t_vb=              "置空错误铃声的终端代码
        set updatetime=100
        set noswapfile

        set noshowmatch        "插入括号时，短暂地跳转到匹配的括号上去
        set matchtime=2        "设置上一条命令的持续时间
        set magic              "设置魔术,支持正则表达式
        set hidden             "允许在有未保存的修改时切换缓冲区，此时的修改由vim负责
        set smartindent        "开启新行时使用只能自动缩进
        set backspace=indent,eol,start  "不设定在插入状态无法用退格键和Delete键删除回车符
        set cmdheight=1        "设定命令行的行数为1
        set textwidth=80       "设定一行输入字符的长度
        set wrap               "自动折行
        set clipboard+=unnamed  "访问系统剪贴板
        set autoread           "自动读取修改了的文件
    endfunction
    call BasicSetting()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"状态栏相关
    function! SetStatusLine()
        set laststatus=2       "显示状态栏（默认值为1，无法显示状态栏）
        set showtabline=2
        set noshowmode
        set statusline=\ %<%F[%1*%M%*%n%R%H]%=\ %y\ %0(%{&fileformat}\ %{&encoding}\ %c:%l/%L%)\             "设置在状态行显示的信息
    endfunction
    call SetStatusLine()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Fold Setting
    function! SetFold()    
        set foldenable         "开始折叠
        " set foldmethod=syntax  "设置语法折叠
        set foldmethod=manual  "设置手动折叠
        set foldmethod=indent  "设置缩进折叠
        set foldcolumn=0       "设置折叠区域的宽度
        setlocal foldlevel=0   "设置折叠层数为...
        " set foldclose=all      "设置为自动关闭折叠
        nnoremap <space> @=((foldclosed(line('.'))<0) ? 'zc' : 'zo')<CR>     "用空格键来开关折叠
    endfunction
    call SetFold()    
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Color Setting
    " let fortran_free_source = 1
    function! SetColor()
        set t_Co=256
        syntax on              "自动语法高亮
        function! MyColorScheme(name, bg)
            execute 'set background='.a:bg
            " execute 'colorscheme '.a:name
            " hi Normal ctermbg=NONE guibg=NONE
            if a:name ==? 'NeoSolarized'
                let g:neosolarized_vertSplitBgTrans=0
                let g:neosolarized_termtrans=1
                execute 'colorscheme '.a:name
                hi Terminal ctermbg=NONE guibg=#073642
                hi Pmenu        cterm=NONE ctermbg=33  ctermfg=234 gui=NONE guibg=#0080fe  guifg=black
                hi PmenuSel     cterm=BOLD ctermbg=34 ctermfg=234 gui=bold guibg=#3bb143  guifg=black
                if a:name ==? 'dark'
                    " hi StatusLine   cterm=reverse
                    " hi Folded       cterm=BOLD ctermbg=black     ctermfg=246
                    " hi SignColumn   cterm=NONE ctermbg=black     ctermfg=none   gui=NONE guifg=NONE guibg=#073642
                    " hi Todo         cterm=NONE ctermbg=black     ctermfg=yellow
                else
                    " hi StatusLine   cterm=reverse
                    " hi Folded       cterm=BOLD ctermbg=lightgrey     ctermfg=246
                    " hi StatusLineNC cterm=none ctermbg=grey
                    " hi SignColumn   cterm=NONE ctermbg=lightgrey ctermfg=none gui=NONE guifg=NONE  guibg=#eee8d5
                endif
            elseif a:name ==? 'dracula'
                if &background ==? 'dark'
                    hi Pmenu cterm=NONE ctermbg=blue ctermfg=234
                    hi PmenuSel     cterm=BOLD ctermbg=darkgreen ctermfg=234
                else
                    hi Pmenu        cterm=BOLD ctermbg=blue      ctermfg=white
                    hi PmenuSel     cterm=BOLD ctermbg=darkcyan  ctermfg=yellow
                endif
            endif
        endfunction

        if has('gui_running')
            set guicursor=a:block-blinkon0
            set guifont=Meslo\ LG\ S\ for\ Powerline:h14
            set guifont=Hack:h14
            set guioptions=t
            set background=light
            set transparency=5
            call MyColorScheme('NeoSolarized', 'light')
            call MyColorScheme('NeoSolarized', 'dark')
        elseif $FROM_SSH ==? 'TRUE'
            call MyColorScheme('Monokai', 'light')
        else 
            if has('termguicolors')
                " fix bug for vim
                set t_8f=[38;2;%lu;%lu;%lum
                set t_8b=[48;2;%lu;%lu;%lum
                " 目前在kitty和alacrity中设置truecolor会出现一些问题
                " kitty:
                "   在vim中打开的终端不透明，且颜色出错
                " alacrity:
                "   在vim中打开的终端不透明
                " enable true color
                set termguicolors
                " let g:term_colors=['#073642', '#dc322f', '#859900', '#b58900', '#268bd2', '#d33682', '#2aa198', '#eee8d5', '#002b36', '#cb4b16', '#586e75', '#657b83', '#839496', '#6c71c4', '#93a1a1', '#fdf6e3']
                " call term_setansicolors(, term_colors)
            endif
            call MyColorScheme('dracula', 'light')
            call MyColorScheme('Monokai', 'dark')
            call MyColorScheme('NeoSolarized', 'dark')
        endif

        function! BackgroundToggle()
            if &background ==? 'light'
                silent !solarized dark
                call MyColorScheme(g:colors_name, 'dark')
            else
                silent !solarized light
                call MyColorScheme(g:colors_name, 'light')
            endif
        endfunction
        nnoremap <F2> :call BackgroundToggle()<CR>
    endfunction
    call SetColor()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Tab and Buffer
    function! SetTabBuffer()
        nnoremap <C-t>n :tabnew<CR>
        nnoremap <C-t>c :tabclose<CR>

        " "tab操作快捷键
        " map <leader>tn :tabnext<cr>
        " map <leader>tp :tabprevious<cr>
        " map <leader>td :tabnew<cr>
        " map <leader>tc :tabclose<cr>
        " map <leader>tm :tabmove<cr>

        "在当前缓冲区路径下打开一个新的tab
        "在同一个目录下编辑文件时非常有用
        map <c-t>e :tabedit <c-r>=expand("%:p:h")<cr>/
        " "缓冲区操作快捷方式
        nnoremap <C-b>n :bnext<CR>
        nnoremap <C-b>p :bprevious<CR>
        inoremap <C-b>n <Esc>:bnext<CR><insert>
        inoremap <C-b>p <Esc>:bprevious<CR>
        "再次打开时回到最后一次进行修改的地方
        augroup return_where_leave
            autocmd BufReadPost *
                \ if line("'\"") > 0 && line("'\"") <= line("$") |
                \   exe "normal! g'\"" |
                \ endif
        augroup END
        "记住缓冲区关闭时的信息
        set viminfo^=%
    endfunction
    call SetTabBuffer()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                            Key Mapping                             "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" For vimrc
"将map leader映射为逗号","
    let mapleader = ','
    function! SetVimrc()
        "将map leader映射为逗号","
        let mapleader = ','
        nmap <Leader>s :w!<cr>      "快速保存
        nmap <Leader>S :wq<cr>      "快速保存并退出
        nmap <Leader>q :q<cr>       "不保存退出
        nmap <Leader>Q :q!<cr>      "不保存强制退出
        map <silent> <leader>z :source $MYVIMRC<cr>  "重载.vimrc
        map <silent> <leader><leader>e  :e $MYVIMRC<cr>   "编辑.vimrc
        augroup reload_vimrc
            "编辑.vimrc过后立即重载
            autocmd!
            autocmd BufWritePost $MYVIMRC source %
            autocmd BufWritePost,SourceCmd $MYVIMRC YcmRestartServer
            autocmd BufWritePost $MYVIMRC AirlineRefresh
        augroup END
    endfunction
    call SetVimrc()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" For window
    function! SetWindow()
        "窗口分割时，进行切换的按键热键需要连接两次，比如从下方窗口移动
        "光标到上方窗口，需要<c-w><c-w>k,非常麻烦，现在重映射为<c-k>，切换
        "的时候会变得非常方便
        nnoremap <Leader><Leader>l <C-w>l
        nnoremap <Leader><Leader>h <C-w>h
        nnoremap <Leader><Leader>k <C-w>k
        nnoremap <Leader><Leader>j <C-w>j
        " nnoremap <C-h> <C-w>h<C-w>
        " nnoremap <C-j> <C-w>j<C-w>
        " nnoremap <C-k> <C-w>k<C-w>
        " nnoremap <C-l> <C-w>l<C-w>
    endfunction
    call SetWindow()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                           File Setting                             "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Buffer
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Fortran
    function! SetFortran()
        let fortran_more_precise=1
        let fortran_do_enddo=1
        let fortran_have_tabs=1
        let fortran_fold=1
        let fortran_fold_conditionals=1
        let s:extfname=expand('%:e')
        function! FreeFormat()
            set syntax=fortran
            let b:fortran_fixed_source=0
            set syntax=text
            set syntax=fortran
        endfunction
        au BufNewFile,BufReadPost *.f90,*.F90 call FreeFormat()
    endfunction
    call SetFortran()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Latex
    function! SetLatex()
        let g:tex_flavor = 'latex' 
        let g:tex_conceal= 0
        let g:tex_fast = 'bcmMPrsSvV'
    endfunction
    call SetLatex()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                       Plugin Configuration                         "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" YCM
    function! SetYCM()
        "手动关闭开启YCM
        function! YCMTrigger()
            if g:ycm_auto_trigger == 0
                let g:ycm_auto_trigger = 1
                echom 'YCM turns on'
            else
                let g:ycm_auto_trigger = 0
                echom 'YCM turns off'
            endif
        endfunction
        nnoremap <leader>y :call YCMTrigger()<CR>

        " 延迟加载
        augroup load_ycm
            autocmd!
            autocmd CursorHold,CursorHoldI *  call plug#load('YouCompleteMe')
                        \| call youcompleteme#Enable() | autocmd! load_ycm
        augroup END

        "让Vim的补全菜单行为与一般IDE一致（参考VimTip1228）
        " 绝对不要加 longest
        set completeopt=menu,menuone
        "打开错误诊断
        nmap <F7> :YcmDiags<CR>
            "上下左右键的行为会显示其他信息（insert mode shortcuts）
            " inoremap <expr> <Down>     pumvisible() ? '<C-n>' : '<Down>'
            " inoremap <expr> <Up>       pumvisible() ? '<C-p>' : '<Up>'
            " inoremap <expr> <c-d> pumvisible() ? '<PageDown><C-p><C-n>' : '<PageDown>'
            " inoremap <expr> <c-u> pumvisible() ? '<PageUp><C-p><C-n>' : '<PageUp>'
        
            "ipython解释器路径
            " 如果vim支持python3而不是2,就需指定python解释器路径
            " let g:ycm_server_python_interpreter='/usr/bin/python'
            " let g:ycm_path_to_python_interpreter='/usr/bin/python'
        "回车选中当前项
        let g:ycm_key_list_stop_completion = ['<CR>']
        "关闭加载.ycm_extra_conf.py提示
        let g:ycm_confirm_extra_conf=0
        "开启YCM基于标签引擎
        let g:ycm_collect_identifiers_from_tags_files=1
        "语法关键字补全
        let g:ycm_seed_identifiers_with_syntax=1
        "在注释中也能补全
        let g:ycm_complete_in_comments = 1
        "在字符串中也能补全
        let g:ycm_complete_in_strings = 1
        "注释和字符串中的文字也会被收入补全
        let g:ycm_collect_identifiers_from_comments_and_strings = 1
        "如果选中项基于语义,则在文件上方弹出其详细信息
        let g:ycm_add_preview_to_completeopt = 0 "New one
        "补全后自动关闭预览窗口,如果上一项为0,则无关紧要
        let g:ycm_autoclose_preview_window_after_completion= 1
        "如果上上一项为0或上一项为1,则无关紧要
        let g:ycm_autoclose_preview_window_after_insertion = 1
        
        let g:ycm_key_invoke_completion = '<leader><leader>s'
        let g:ycm_semantic_triggers = {
                    \'c,cpp,python,f90': ['re!\w{2}']
                    \}

        let g:ycm_use_ultisnips_completer = 1 "New one
        "跳转到定义处
        nnoremap <leader>g :YcmCompleter GoTo<CR>
        "改正错误，只适用于 C-family language.
        nmap <tab> :YcmCompleter FixIt<CR>
        "YCM 黑名单
        let g:ycm_filetype_blacklist = {
                    \ 'tagbar'  : 1,
                    \ 'qf'  : 1,
                    \ 'notes'  : 1,
                    \ 'unite'  : 1,
                    \ 'text'  : 1,
                    \ 'vimwiki' : 1,
                    \ 'pandoc'  : 1,
                    \ 'infolog' : 1,
                    \ 'mail'    : 1,
                    \}
        "YCM 白名单
        " let g:ycm_filetype_whitelist = {
        "     \ 'python': 1,
        "     \ 'c' : 1,
        "     \ 'cpp': 1,
        "     \ 'f90': 1,
        "     \ 'md': 1,
        "     \ 'tex': 1,
        "     \ 'bash': 1,
        "     \}
        "判断是否再虚拟环境中，确保YouCompleteMe能找到相应的site packages文件夹
        "python with virtualenv support
        " py << EOF
        " import os
        " import sys
        " if 'VIRTUAL_ENV' in os.environ:
        "     project_base_dir = os.environ['VIRTUAL_ENV']
        "     activate_this = os.path.join(project_base_dir,'bin/activate_this.py')
        "     execfile(activate_this, dict(__file__=activate_this))
        " EOF
    endfunction
    call SetYCM()
    
" Ultisnips
    function! SetUltiSnips()
        let g:UltiSnipsSnippetDirectories=['UltiSnips']
        let g:UltiSnipsSnippetsDir='~/.vim/UltiSnips'
        let g:UltiSnipsExpandTrigger='<c-j>'
        let g:UltiSnipsJumpForwardTrigger='<c-j>'
        let g:UltiSnipsJumpBackwardTrigger='<c-k>'
        let g:UltiSnipsEditSplit='vertical'
            " " make YCM compatible with UltiSnips
            " function! g:UltiSnips_Complete()
            "     call UltiSnips#ExpandSnippet()
            "     if g:ulti_expand_res == 0
            "         if pumvisible()
            "             return '\<c-n>'
            "         else
            "             " call UltiSnips#JumpBackwards()
            "             " if g:ulti_jump_backwards_res == 0
            "             "     return '\<s-n>'
            "             " endif
            "         endif
            "     endif
            " endfunction
            " " function! g:UltiSnips_Reverse()
            "     " call UltiSnips#JumpForwards()
            "     " if g:ulti_jump_forwards_res == 0
            "     " endif
            " " endfunction
            " au InsertEnter * exec 'inoremap <silent> ' . g:UltiSnipsExpandTrigger . ' <C-R>=g:UltiSnips_Complete()<cr>'
            " " au InsertEnter * exec 'inoremap <silent> ' . g:UltiSnipsJumpBackwardTrigger . '<C-R>=g:UltiSnips_Reverse()<cr>'
    endfunction
    call SetUltiSnips()

" Neocomplete
    " function! SetNeocomplete()
    "
    " endfunction
    " call SetNeocomplete()
    
" Nerdtree
    " map <F4> :NERDTreeToggle<CR>     "设置F4为打开nerdtree的快捷键
    let g:NERDTreeWinSize=30

" Tagbar
    function! SetTagbar()
        " 打开 tagbar 时自动跳转到 tagbar 窗口
        let g:tagbar_autofocus=1
        " 选中 tag 后跳转至定义处并自动关闭 tagbar 窗口
        let g:tagbar_autoclose=0
        " 在左侧打开
        " let g:tagbar_left=1
        " 在上方打开 tagbar 窗口
        " let g:tagbar_vertical=20
        " 设置宽度 
        let g:tagbar_width=30
        function! TagbarForward()
            if exists('t:NERDTreeBufName') && bufwinnr(bufnr(t:NERDTreeBufName)) != -1
                TagbarOpen fj
            else
                let g:tagbar_left = 1
                " TagbarOpen fjc
                TagbarOpen fj
                let g:tagbar_left = 0
            endif
        endfunction
        nnoremap <leader>f :call TagbarForward()<CR>
        function! ToggleNERDTreeAndTagbar()
            " 获取当前窗口的缓冲区编号
            let current_bufid = bufnr('%')
            " 检查 NERDTree 是否有打开
            if exists('t:NERDTreeBufName')
                let nerdtree_open = bufwinnr(t:NERDTreeBufName) != -1
            else
                let nerdtree_open = 0
            endif
            let tagbar_open = bufwinnr('__Tagbar__') != -1
            " 根据当前状态采取适当操作
            if nerdtree_open
                if tagbar_open
                    TagbarToggle
                    NERDTreeToggle
                else
                    " 跳转到 NERDTree 窗口
                    let nerdtree_winid = bufwinnr(t:NERDTreeBufName)
                    exe nerdtree_winid . 'wincmd w'
                    " 获取 NERDTree 窗口高度
                    let nerdtree_height = winheight(nerdtree_winid)
                    " 在下方打开 Tagbar
                    let g:tagbar_left = 0
                    let g:tagbar_vertical = nerdtree_height / 2
                    TagbarToggle 
                endif 
            else
                if tagbar_open
                    TagbarToggle
                endif 
                NERDTreeToggle
                let g:tagbar_vertical = winheight(bufwinnr(t:NERDTreeBufName)) / 2
                TagbarToggle
            endif
            " 跳回到初始窗口
            exe bufwinnr(current_bufid) . 'wincmd w'
            let g:tagbar_vertical = 0
        endfunction
        nnoremap <F8> :call ToggleNERDTreeAndTagbar()<CR>
        " Add support for markdown files, 配合插件 markdown2ctags
        let g:tagbar_type_markdown = {
            \ 'ctagstype': 'markdown',
            \ 'ctagsbin': '~/.vim/vim_plugin/markdown2ctags/markdown2ctags.py',
            \ 'ctagsargs': '-f - --sort=yes',
            \ 'kinds': [
                \ 's:sections',
                \ 'i:images',
            \ ],
            \ 'sro': '|',
            \ 'kind2scope': {
                \ 's': 'section', 
            \ },
            \ 'sort': 0,
        \ }
    endfunction 
    call SetTagbar()

" Nerdcommenter
    function! SetNerdcommenter()
        let g:NERDSpaceDelims = 1
        let g:NERDCompactSexyComs = 1
        let g:NERDDefaultAlign = 'left'
        let g:NERDAltDelims_java = 1
        let g:NERDCommentEmptyLines = 1
        let g:NERDTrimTrailingWhitespace = 1
    endfunction 
    call SetNerdcommenter()

" Vimtex
    function! SetVimtex()
        if empty(v:servername) && exists('*remote_startserver')
            call remote_startserver('TEX')
        endif
        let g:vimtex_enabled = 1
        let g:vimtex_format_enabled = 1
        function! VimtexTrigger()
            if g:vimtex_enabled == 0
                let g:vimtex_enabled = 1
                echom 'vimtex turns on'
            else
                let g:vimtex_enabled = 0
                echom 'vimtex turns off'
            endif
        endfunction
        " nnoremap <leader>v :call VimtexTrigger()<CR>
        " automatically jump to the first error 
        " but not work well with continuous compilation
        let g:vimtex_quickfix_autojump = 0
        " specify PDF viewer
        let g:vimtex_view_method = 'skim'

        " function! CloseViewers()
        "     if executable('xdotool') && exists('b:vimtex')
        "         \ && exists('b:vimtex.viewer') && b:vimtex.viewer.xwin_id > 0
        "     call system('xdotool windowclose '. b:vimtex.viewer.xwin_id)
        "     endif
        " endfunction

        " augroup vimtex_event_2
        "     au!
        "     au User VimtexEventQuit call CloseViewers()
        " augroup END

        " make YCM work
        if !exists('g:ycm_semantic_triggers')
            let g:ycm_semantic_triggers = {}
        endif
        au VimEnter,BufNewFile,BufReadPre *.tex
                    \   if !exists('g:ycm_semantic_triggers')
                    \ |     let g:ycm_semantic_triggers = {}
                    \ | endif
                    \ | let g:ycm_semantic_triggers.tex = g:vimtex#re#youcompleteme
        " let g:ycm_semantic_triggers.tex = g:vimtex#re#youcompleteme
        let g:vimtex_compiler_latexmk = {
            \ 'background' : 1,
            \ 'build_dir' : '',
            \ 'callback' : 1,
            \ 'continuous' : 1,
            \ 'executable' : 'latexmk',
            \ 'options' : [
            \   '-verbose',
            \   '-file-line-error',
            \   '-synctex=1',
            \   '-interaction=nonstopmode',
            \ ],
            \}
        let g:vimtex_syntax_minted = [
            \ {
            \   'lang' : 'python',
            \   'ignore' : [
            \       'pythonEscape',
            \       'pythonBEscape',
            \       ],
            \ }
            \]
    endfunction
    call SetVimtex()

" Vim-markdown
    function! SetVimmarkdown()
        " YAML front matter
        let g:vim_markdown_frontmatter = 1
        " fenced code block languages
        let g:vim_markdown_fenced_languages = ['python=py', 'viml=vim', 'bash=sh', 'c++=cpp']
        let g:vim_markdown_folding_disabled = 1
        " set header folding level
        let g:vim_markdown_folding_level = 6
        let g:vim_markdown_toc_autofit = 1
        " adjust new list item indent
        let g:vim_markdown_new_list_item_indent = 2
        " disable math conceal with LaTex math syntax enabled
        " let g:tex_conceal = ""
        let g:vim_markdown_math = 1
        " syntax concealing
        let g:vim_markdown_conceal = 0
    endfunction
    call SetVimmarkdown()

" Markdown-Preview
    function! SetMarkdownPreview()
        " 设置为 1 可以在打开markdown文件时自动打开浏览器预览，只在打开markdown文件时打开一次
        let g:mkdp_auto_start= 0
        " 设置为 1 在编辑markdown的时候检查预览窗口是否打开，没有则打开
        let g:mkdp_auto_open= 1
        " 切换 buffer 的时候自动关闭预览窗口，设置为 0 则不自动关闭
        let g:mkdp_auto_close= 0
        " 设置为 1 则只在保存文件或退出插入模式的时候更新预览，默认实时预览
        let g:mkdp_refresh_slow= 0
        " 设置为 1 则所有文件都可以用命令 MarkdownPreview
        " 进行预览，默认只有markdown文件可以使用该命令
        let g:mkdp_command_for_global= 0

        function! MarkdownPreviewTrigger()
            if g:mkdp_server_started == 0
                :MarkdownPreview
            else
                :MarkdownPreviewStop
            endif
        endfunction
        nnoremap <c-p> :call MarkdownPreviewTrigger()<CR>
        inoremap <c-p> :call MarkdownPreviewTrigger()<CR>
    endfunction 
    call SetMarkdownPreview()

" Easymotion
    function! SetEasymotion()
        " 关闭默认映射
        let g:Easymotion_do_mapping = 1
        " 大小写不敏感
        let g:Easymotion_smartcase = 1
        " 跨窗口搜索一（两）个字母
        map f <Plug>(easymotion-overwin-f)
        map s <Plug>(easymotion-overwin-f2)
        " 双向搜索词头和词尾
        map <Leader>w <Plug>(easymotion-bd-w)
        map <Leader>e <Plug>(easymotion-bd-e)
        " 覆盖 vim 字符串搜索，可以跨窗口
        " map / <Plug>(easymotion-sn)
        " line motion 
        map <Leader>l <Plug>(easymotion-lineforward)
        map <Leader>j <Plug>(easymotion-j)
        map <Leader>k <Plug>(easymotion-k)
        map <Leader>h <Plug>(easymotion-linebackward)
    endfunction
    call SetEasymotion()

" Incsearch (fuzzy and easymotion)
    function! SetIncsearch()
        " 结合 easymotion 后没有必要再需要区分往前、往后搜索
        " 增量搜索与 easymotion 结合
        function! s:incsearch_config(...) abort
            return incsearch#util#deepextend(deepcopy({
            \   'modules': [incsearch#config#easymotion#module({'overwin': 1})],
            \   'keymap': {
            \     "\<CR>": '<Over>(easymotion)'
            \   },
            \   'is_expr': 0
            \ }), get(a:, 1, {}))
        endfunction
        noremap <silent><expr> / incsearch#go(<SID>incsearch_config({'is_stay': 1}))
        " 增量模糊搜索与 easymotion 结合
        function! s:config_easyfuzzymotion(...) abort
            return extend(copy({
            \   'converters': [incsearch#config#fuzzyword#converter()],
            \   'modules': [incsearch#config#easymotion#module({'overwin': 1})],
            \   'keymap': {
            \     "\<CR>": '<Over>(easymotion)'
            \   },
            \   'is_expr': 0,
            \   'is_stay': 1,
            \ }), get(a:, 1, {}))
        endfunction
        noremap <silent><expr> z/ incsearch#go(<SID>config_easyfuzzymotion())
    endfunction 
    call SetIncsearch()

" Fzf
    function! SetFzf() 
        let g:fzf_action = {
        \   'alt-t': 'tab split',
        \   '-': 'split',
        \   '/': 'vsplit' }
        let g:fzf_layout={'down': '~50%'}
        " let g:fzf_layout={'window': 'enew'}
        let g:fzf_colors = {'border':  ['fg', 'Pmenu']}
    endfunction
    call SetFzf() 

" ALE
    function! SetALE() 
        autocmd FileType * noremap <buffer> <Leader><Leader>c :ALELint<CR>
        let g:ale_lint_on_enter = 1
        let g:ale_lint_on_text_changed = 'never'
        let g:ale_lint_on_save = 1
        let g:ale_set_quickfix = 1
        " if show the error column forever.
        let g:ale_sign_column_always = 0
        let g:ale_sign_error = '••'
        " 只有来自 g:ale_linters 和 b:ale_linters 中的 linters 会被启动
        let g:ale_linters_explicit = 1
        " bash 文件会运行 sh 的 linter
        let g:ale_linter_aliases = {'bash': 'sh',
                                    \'zsh': 'sh',
                                    \'vimwiki': 'markdown',
                                    \}
        let g:ale_linters_ignore = {'python': ['pylint'],
                                   \}
        let g:ale_linters = {'python': ['pyls'],
                            \'sh': ['shellcheck'],
                            \'vim': ['vint'],
                            \'fortran': ['gcc'],
                            \'c':['clang'],
                            \'tex':['lacheck', 'chktex'],
                            \}
        let g:ale_sh_shellcheck_exclusions = 'SC1090,SC2005,SC2046,SC2086,SC2155'

        let g:ale_fortran_gcc_executable = 'gfortran'
        let g:ale_fortran_gcc_options = '-Wall'
        let g:ale_fortran_gcc_use_free_form = 1
        "
        let g:ale_fixers = {
                    \   'c': [
                    \       'clang-format',
                    \   ],
                    \   'python': [
                    \       'yapf',
                    \       'trim_whitespace',
                    \       'remove_trailing_lines',
                    \   ],
                    \   'sh': [
                    \       'shfmt',
                    \       'trim_whitespace',
                    \       'remove_trailing_lines',
                    \   ],
                    \}
        " customize format for error and warning messages.
        " let g:ale_echo_msg_error_str = 'E'
        " let g:ale_echo_msg_warning_str = 'W'
        " let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
        nmap <silent> <C-k> <Plug>(ale_previous_wrap)
        nmap <silent> <C-j> <Plug>(ale_next_wrap)
        nmap <silent> <F3> <Plug>(ale_fix)
    endfunction 
    call SetALE() 

" Autoformat
    function! SetAutoformat()
        autocmd FileType c,fortran noremap <buffer> <F10> :Autoformat<CR>
        " nmap <buffer> <F8> :Autoformat<CR>
        " 插件会自动设置这两项，yapf 的优势在于代码风格的可定制性。
        let g:autoformat_autoindent=0
        let g:autoformat_retab=0
        let g:autoformat_remove_trailing_spaces=0
        " let g:autoformat_verbosemode=1
        autocmd FileType vim,tex let b:autoformat_autoindent=0
        " au BufWrite * :Autoformat
    endfunction
    call SetAutoformat()

" Pangu
    function! SetPangu()
        autocmd BufWritePre *.markdown,*.md,*.text,*txt,*.wiki,*.cnx call PanGuSpacing()
    endfunction
    call SetPangu()

" AsyncRun
    function! SetAsyncRun()
        let $PYTHONUNBUFFERED=1
        " quick run
        imap <F5> <Esc>:call <SID>compile_and_run()<CR>
        nmap <F5> :call <SID>compile_and_run()<CR>
        function! s:compile_and_run()
            exec 'w'
            if &filetype ==? 'fortran'
                exec 'AsyncRun! mpifort % -o %< -qopenmp -fpp -mkl; time ./%<'
            elseif &filetype ==? 'c'
                exec 'AsyncRun! gcc % -o %<; time ./%<'
            elseif &filetype ==? 'cpp'
                exec 'AsyncRun! g++ -std=c++11 % -o %<; time ./%<'
            elseif &filetype ==? 'java'
                exec 'AsyncRun! javac %; time java /%<'
            elseif &filetype ==? 'sh'
                exec 'AsyncRun! time bash %'
            elseif &filetype ==? 'python'
                exec 'AsyncRun! -raw python %'
            elseif &filetype ==? 'tex'
                exec 'VimtexCompile'
            elseif &filetype ==? 'ruby'
                exec 'AsyncRun! time ruby %'
            endif
        endfunction 
        " bind <F9> to open quickfix window rapidly.
        nmap <F9> :call asyncrun#quickfix_toggle(10)<cr>
        " like Emacs, use <M-x> to type commands.
        set timeoutlen=500 ttimeoutlen=100
        exec "set <M-x>=\ex"
        imap <M-x> <Esc>:AsyncRun
        nmap <M-x> :AsyncRun
        " ring bell when finished.
        let g:asyncrun_exit = "silent call system('play ~/Music/notify/facebook.wav  &')"
        " open quickfix window in right way.
        augroup vimrc
            autocmd!
            " autocmd QuickFixCmdPost * call asyncrun#quickfix_toggle(10,1)
            autocmd User AsyncRunStop call asyncrun#quickfix_toggle(10,1)
        augroup END
    endfunction
    call SetAsyncRun()

" Powerline
    function! SetPowerline()
        if has('python')
            python from powerline.vim import setup as powerline_setup
            python powerline_setup()
            python del powerline_setup
        else
            python3 from powerline.vim import setup as powerline_setup
            python3 powerline_setup()
            python3 del powerline_setup
        endif
    endfunction
    " call SetPowerline()

" Airline
    function! SetAirline()
        " let g:airline_theme='powerlineish'
        " let g:airline_theme='papercolor'
        let g:airline_theme='minimalist'
        let g:airline_powerline_fonts = 1
        let g:airline#extensions#tabline#enabled=1
        let g:airline#extensions#tabline#show_tabs = 1
        let g:airline_extensions#tabline#show_buffers = 1
        " let g:airline#extensions#tabline#alt_sep = 1
        let g:airline#extensions#tabline#buffer_nr_show = 1
        " integration with ALE
        let g:airline#extensions#ale#enabled = 1
        " let g:airline_extensions = ['vimtex', 'tagbar']

    endfunction
    call SetAirline()

" Promptline
    function! SetPromptline()
        let git_sha_slice = {
                    \'function_name': 'git_sha',
                    \'function_body': [
                        \'function git_sha {',
                        \'  local sha',
                        \'  sha=$(git rev-parse --short HEAD 2>/dev/null) || return 1',
                        \'  printf "%s" "$sha"',
                        \'}']}

        " let g:promptline_preset = 'powerlineclone'
        let g:promptline_preset = {
                    \'c'    : [ promptline#slices#user(), promptline#slices#battery({'threshold': 30}) ],
                    \'b'    : [ promptline#slices#python_virtualenv() ],
                    \'a'    : [ promptline#slices#cwd({'dir_limit': 2}) ],
                    \'y'    : [ promptline#slices#vcs_branch() ],
                    \'warn' : [ promptline#slices#last_exit_code() ],
                    \'options': {
                        \'left_only_sections' : [ 'c', 'b', 'a', 'y', 'warn' ]}
                    \}
        " 可以传入字典
        " let g:promptline_theme = 'airline'
        let g:promptline_theme = {
                    \'c'    : [ 253, 24 ],
                    \'b'    : [ 252, 31 ],
                    \'a'    : [ 8, 249 ],
                    \'y'    : [ 252, 31 ],
                    \'warn' : [ 232, 166 ]
                    \}
        let g:promptline_powerline_symbols = 1
    endfunction
    " call SetPromptline()

" Tmuxline
    function! SetTmuxline()
        " let g:tmuxline_theme = 'iceberg'
        " let g:tmuxline_preset = {
                    \'a'    : '#S',
                    \'b'    : '#W',
                    \'win'  : ['#I', '#W'],
                    \'cwin' : ['#I', '#W', '#F'],
                    \'y'    : ['#(buffer_size)', '%R'],
                    \'z'    : '#h',
                    \}
    endfunction
    " call SetTmuxline()

" Easy-Align
    function! SetEasyAlign()
        xmap ga <Plug>(EasyAlign)
        nmap ga <Plug>(EasyAlign)
    endfunction
    call SetEasyAlign()

" IndentLine
    " let g:indentLine_setConceal = 0
    nmap <leader>i :IndentLinesToggle<cr>
